routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//get, post, put, patch, delete http verb

Auth::routes();



Route::middleware(['auth', 'ageChecker'])->group(function (){

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/profile', 'UserController@profile')->name('users.profile');

    Route::post('/products/{product}/review', 'PublicController@review')->name('products.review');

    /*Frontend*/
    Route::get('/products', 'PublicController@products');
    Route::get('/product_details', 'PublicController@show');

    Route::prefix('admin')->group(function (){
        /*Category routes*/
        Route::get('/categories/download-pdf', 'CategoryController@downloadPdf')->name('categories.download_pdf');
        Route::get('/categories/download-excel', 'CategoryController@downloadExcel')->name('categories.download_excel');
        Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/products', 'ProductController');
        Route::resource('/sizes', 'SizeController');
        Route::resource('/roles', 'RoleController');


        Route::resource('/orders', 'OrderController');
        Route::resource('/users', 'UserController');


        Route::get('/users', 'UserController@index')->name('users.index');
        Route::get('/users/{user}', 'UserController@show')->name('users.show');
        Route::get('/users/{user}/edit', 'UserController@edit')->name('users.edit');
        Route::put('/users/{user}', 'UserController@update')->name('users.update');
        Route::delete('/users/{user}', 'UserController@destroy')->name('users.destroy');





        Route::get('/roles', 'RoleController@index')->name('roles.index');
        Route::get('/roles/{role}', 'RoleController@show')->name('roles.show');
        Route::get('/roles/{role}/edit', 'RoleController@edit')->name('roles.edit');
        Route::put('/roles/{role}', 'RoleController@update')->name('roles.update');
        Route::delete('/roles/{role}', 'RoleController@destroy')->name('roles.destroy');


        Route::delete('/system/notifications', 'NotificationController@index')->name('notifications.all');


//    Route::get('/categories', 'CategoryController@index')->name('categories.index');//list
//    Route::get('/categories/create', 'CategoryController@create')->name('categories.create');//create
//    Route::post('/categories', 'CategoryController@store')->name('categories.store');//store
//    Route::get('/categories/{category}', 'CategoryController@show')->name('categories.show');//show
//    Route::get('/categories/{category}/edit', 'CategoryController@edit')->name('categories.edit');//edit
//    Route::put('/categories/{category}', 'CategoryController@update')->name('categories.update');//update
//    Route::delete('/categories/{category}', 'CategoryController@destroy')->name('categories.destroy');//destroy


//    put/patch -> update
//    delete -> delete
//    post -> store

        /*Product routes*/


    });

});

//Route::get('/home', function (){
//    return view('backend.home');
//});


Route::get('/cart', 'CartController@shoppingCart')->name('cart');
Route::get('/cart/{productId}/remove', 'CartController@removeFromCart')->name('carts.remove_product');
Route::post('/add-to-cart', 'CartController@addToCart');
Route::get('/{categoryId?}', 'PublicController@index');
Route::get('/category/{category}', 'PublicController@productsByCategoryId')->name('products_by_category');
Route::get('/products/{product}', 'PublicController@show')->name('product_details');


/**Check out Routes */
Route::get('/checkout/index', 'CheckoutController@index')->name('checkout.index');
Route::post('/checkout/store', 'CheckoutController@store')->name('checkout.store');


Route::get('/cart/index', 'CartController@index')->name('cart.index');
Route::post('/cart/store', 'CartController@store')->name('cart.store');
//Route::get('/cart/update', 'CheckoutController@index')->name('cart.index');
//Route::post('/cart/delete', 'CheckoutController@store')->name('cart.delete');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['category_id', 'title', 'description', 'picture', 'is_active', 'price'];

    /*
     * Relationship
     * */
    public function category()// inverse
    {
        return $this->belongsTo(Category::class);
    }

    public function sizes()
    {
        return $this->belongsToMany(Size::class);
    }

    //1 to n polymorphic relation
    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }
    public function orders(){

        return $this->belongsTo(Order::class);

    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use App\Size;
use Carbon\Carbon;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Image;

class ProductController extends Controller
{

//    public function __construct()
//    {
//        $this->middleware('auth');
//    }

    public function index()
    {
        $products = Product::orderBy('created_at', 'desc')->get();
//        $products = Product::onlyTrashed()->orderBy('created_at', 'desc')->get();
        return view('backend.products.index', compact('products'));
    }

    public function create()
    {

//        $categories = [
//            '1'=>'Category 1',
//            '2'=>'Category 2',
//        ];

        $categories = Category::pluck('title', 'id')->toArray();
        $sizes = Size::pluck('title', 'id')->toArray();
        $selectedSizes = [];

        return view('backend.products.create', compact('categories', 'sizes', 'selectedSizes'));
    }

    public function store(Request $request)
    {
        try{
            $request->validate([
                'title' => 'required|unique:products|max:100',
                'category_id' => 'required|exists:categories,id',
                'description' => 'min:1|max:1000|required',
            ]);

            $requestData = $request->all();

            if ($request->hasFile('picture')) {
                $requestData['picture'] = $this->uploadImage($request->picture, $request->title);
            }

            $requestData['is_active'] = $request->is_active == 'on'?1:0;

            $category = Category::findOrFail($request->category_id);

            $product = $category->products()->create($requestData);

            $product->sizes()->attach($request->size);

            return redirect()->route('products.index')->withStatus('Task was successful!');

        }catch (QueryException $exception){
            return redirect()->back()->withInput()->withErrors($exception->getMessage());
        }

    }

    public function show(Product $product) //dependency injection
//    public function show($id) //dependency injection
    {

//        $product = Product::findOrFail($id);
//        dd($product);
        return view('backend.products.show', compact('product'));
    }

    public function edit(Product $product)
    {
//        $product = Product::findOrFail($id);

        $categories = Category::pluck('title', 'id')->toArray();

        $sizes = Size::pluck('title', 'id')->toArray();

        $selectedSizes = $product->sizes->pluck('id')->toArray();

        return view('backend.products.edit', compact('product', 'categories', 'sizes', 'selectedSizes'));
    }

    public function update(Request $request, Product $product)
    {

        try{

            $requestData = $request->all();

            if ($request->hasFile('picture')) {

                $this->unlink($product->picture);

                $requestData['picture'] = $this->uploadImage($request->picture, $request->title);
            }else{
                $requestData['picture'] = $product->picture;
            }

            $requestData['is_active'] = $request->is_active == 'on'?1:0;

            $product->update($requestData);

            $product->sizes()->sync($request->size);

//            $request->session()->flash('status', 'Task was successful!');

            return redirect()->route('products.index')->withStatus('Task was successful!');

        }catch (QueryException $exception){
            return redirect()->back()->withErrors($exception->getMessage());
        }

    }

    public function destroy(Product $product)
    {

        try{

//            $product = Product::findOrFail($id);
            $product->sizes()->detach();
            $product->delete();

            return redirect()->route('products.index')->withStatus('Task was successful!');

        }catch (QueryException $exception){
            return redirect()->back()->withErrors($exception->getMessage());
        }

    }

    private function uploadImage($file, $name)
    {
        $timestamp = str_replace([' ', ':'], '-', Carbon::now()->toDateTimeString());

        $file_name = $timestamp .'-'.$name. '.' . $file->getClientOriginalExtension();

        $pathToUpload = storage_path().'/app/public/products/';

        Image::make($file)->resize(700, 400)->save($pathToUpload.$file_name);

        return $file_name;
    }

    private function unlink($file)
    {
        $pathToUpload = storage_path().'/app/public/products/';

        if ($file != '' && file_exists($pathToUpload. $file)) {
            @unlink($pathToUpload. $file);
        }
    }

}

resources/views/backend/products/create.blade.php
@extends('backend.layouts.master')

@section('title', 'Category Create')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Products</h1>
{{--        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>--}}
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">Create</h6>
            <a class="btn btn-primary float-right" href="{{ route('products.index') }}">List</a>
        </div>
        <div class="card-body">

            @include('backend.layouts.elements.errors')

            {!! Form::open([
                'route' => 'products.store',
                'files'=>true,
                'enctype'=>'multipart/form-data'

            ]) !!}

{{--            <form action="{{ route('categories.store') }}" method="post">--}}
{{--                @csrf--}}
                @include('backend.products.form')

                <button type="submit" class="btn btn-primary">Submit</button>
{{--            </form>--}}

            {!! Form::close() !!}
        </div>
    </div>
@endsection

@push('js')
    <script>
        // alert('Creating category')
    </script>
@endpush

resources/views/backend/products/edit.blade.php
@extends('backend.layouts.master')

@section('title', 'Products Update')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Products</h1>
        {{--        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>--}}
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">Edit</h6>
            <a class="btn btn-primary float-right" href="{{ route('products.index') }}">List</a>
        </div>
        <div class="card-body">

            @include('backend.layouts.elements.errors')

            {{--            <form action="{{ route('products.update', [$category->id]) }}" method="post">--}}
            {{--                @csrf--}}
            {{--                @method('put')--}}

            {!! Form::model($product, [
                            'route' => ['products.update', $product->id],
                            'method'=>'put',
                            'files'=>true
                        ]) !!}

            @include('backend.products.form')

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        Update
                    </button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

@push('js')
    <script>
        // alert('Creating category')
    </script>
@endpush

resources/views/backend/products/form.blade.php
<div class="form-group">
    {!! Form::label('categoryId', 'Category') !!}

    {!! Form::select('category_id', $categories, null, [
        'class'=>'form-control',
        'id'=>'title',
        'placeholder'=>'Select one'
    ]) !!}
</div>
<div class="form-group">
    {{--                    <label for="title">Title</label>--}}
    {!! Form::label('title', 'Title') !!}
    {{--                    <input name="title" type="text" value="{{ old('title') }}" class="form-control" id="title">--}}
    {!! Form::text('title', null, [
        'class'=>'form-control',
        'id'=>'title',
    ]) !!}
</div>
<div class="form-group">
    <label for="description">Description</label><br>
    {{--                    <textarea name="description"  class="form-control" id="description">{{ old('description') }}</textarea>--}}
    {!! Form::textarea('description', null, [
       'class'=>'form-control',
       'id'=>'title',
   ]) !!}
</div>

<div class="form-group">
    <label for="picture">Image</label><br>
    {{--                    <textarea name="description"  class="form-control" id="description">{{ old('description') }}</textarea>--}}
    {!! Form::file('picture', null, [
       'class'=>'form-control',
       'id'=>'picture',
   ]) !!}
</div>

<p>Sizes : </p>
<div class="form-group form-check">
    @foreach($sizes as $key=>$size)
        <div>
{{--            <input name="size[]" type="checkbox" class="form-check-input" value="{{ $key }}" id="{{ $size }}">--}}
{{--            <label  class="form-check-label" for="{{ $size }}">{{ $size }}</label>--}}
            {!! Form::checkbox('size[]', $key, in_array($key, $selectedSizes), [
               'class'=>'form-check-input',
               'id'=>$size
            ]) !!}
            {{ $size }}
        </div>
    @endforeach
</div>

<div class="form-group">
    <label for="price">Price</label><br>
    {!! Form::number('price', null, [
       'class'=>'form-control',
       'id'=>'price',
   ]) !!}
</div>

<div class="form-group form-check">
    <input name="is_active" type="checkbox" class="form-check-input" id="isActive">
    <label  class="form-check-label" for="isActive">Is Active</label>
</div>

resources/views/backend/products/index.blade.php
@extends('backend.layouts.master')

@section('title', 'Product List')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Products</h1>
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">List</h6>
            <a class="btn btn-primary float-right" href="{{ route('products.create') }}">Create</a>
{{--            <a class="btn btn-danger float-right" href="{{ route('products.trash') }}">Trash</a>--}}
        </div>
        <div class="card-body">

            @include('backend.layouts.elements.message')

            <div class="table-responsive">
                <table class="table table-bordered"  width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Picture</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                        <tr>
                            <td>{{ $product->title }}</td>
                            <td>{{ $product->description }}</td>
                            <td>
                                @if(file_exists(storage_path().'/app/public/products/'.$product->picture) && (!is_null($product->picture)))
                                    <img src="{{ asset('storage/products/'.$product->picture) }}" height="100">
                                @else
                                    No picture
                                @endif
                            </td>
                            <td>{{ $product->is_active? 'Active' : 'Inactive' }}</td>
                            <td>
                                <a href="{{ route('products.show', [$product->id]) }}" class="btn btn-info">Show</a>
                                <a href="{{ route('products.edit', [$product->id]) }}" class="btn btn-warning">Edit</a>

                                <form action="{{ route('products.destroy', [$product->id]) }}" method="post" style="display: inline">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure want to delete ?')">Delete</button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('css')
    <!-- Custom styles for this page -->
    <link href="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

@push('js')
    <!-- Page level plugins -->
    <script src="{{ asset('ui/backend') }}/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('ui/backend') }}/js/demo/datatables-demo.js"></script>
@endpush

resources/views/backend/products/pdf.blade.php
<table border="1" style="width: 100%">
    <thead>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
    @foreach($products as $product)
        <tr>
            <td>{{ $product->title }}</td>
            <td>{{ $product->description }}</td>
            <td>{{ $product->is_active? 'Active' : 'Inactive' }}</td>
        </tr>
    @endforeach
    </tbody>

</table>

resources/views/backend/products/show.blade.php
@extends('backend.layouts.master')

@section('title', 'Category Create')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Products</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">Details</h6>
            <a class="btn btn-primary float-right" href="{{ route('products.index') }}">List</a>
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <td>Title</td>
                    <td>{{ $product->title }}</td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td>{{ $product->description }}</td>
                </tr>
                <tr>
                    <td>Status</td>
                    <td>{{ $product->is_active? 'Active' : 'Inactive' }}</td>
                </tr>
            </table>
        </div>
    </div>
@endsection

@push('js')
    <script>
        // alert('Creating product')
    </script>
@endpush

resources/views/backend/products/trash.blade.php
@extends('backend.layouts.master')

@section('title', 'Deleted Category List')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Categories</h1>
{{--        <a href="{{ route('categories.download_pdf') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">--}}
{{--            <i class="fas fa-download fa-sm text-white-50"></i> Generate PDF Report--}}
{{--        </a>--}}
{{--        <a href="{{ route('categories.download_excel') }}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm">--}}
{{--            <i class="fas fa-file-excel fa-sm text-white-50"></i> Generate Excel Report--}}
{{--        </a>--}}
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">List</h6>
\            <a class="btn btn-primary float-right" href="{{ route('products.index') }}">List</a>
        </div>
        <div class="card-body">

            @include('backend.layouts.elements.message')

            <div class="table-responsive">
                <table class="table table-bordered"  width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                        <tr>
                            <td>{{ $product->title }}</td>
                            <td>{{ $product->description }}</td>
                            <td>{{ $product->is_active? 'Active' : 'Inactive' }}</td>
                            <td>
                                <a href="{{ route('products.show', [$product->id]) }}" class="btn btn-info">Show</a>
                                <a href="{{ route('products.edit', [$product->id]) }}" class="btn btn-warning">Edit</a>

                                <form action="{{ route('products.destroy', [$product->id]) }}" method="post" style="display: inline">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure want to delete ?')">Delete</button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('css')
    <!-- Custom styles for this page -->
    <link href="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

@push('js')
    <!-- Page level plugins -->
    <script src="{{ asset('ui/backend') }}/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('ui/backend') }}/js/demo/datatables-demo.js"></script>
@endpush