routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//get, post, put, patch, delete http verb

Auth::routes();



Route::middleware(['auth', 'ageChecker'])->group(function (){

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/profile', 'UserController@profile')->name('users.profile');

    Route::post('/products/{product}/review', 'PublicController@review')->name('products.review');

    /*Frontend*/
    Route::get('/products', 'PublicController@products');
    Route::get('/product_details', 'PublicController@show');

    Route::prefix('admin')->group(function (){
        /*Category routes*/
        Route::get('/categories/download-pdf', 'CategoryController@downloadPdf')->name('categories.download_pdf');
        Route::get('/categories/download-excel', 'CategoryController@downloadExcel')->name('categories.download_excel');
        Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/products', 'ProductController');
        Route::resource('/sizes', 'SizeController');
        Route::resource('/roles', 'RoleController');


        Route::resource('/orders', 'OrderController');
        Route::resource('/users', 'UserController');


        Route::get('/users', 'UserController@index')->name('users.index');
        Route::get('/users/{user}', 'UserController@show')->name('users.show');
        Route::get('/users/{user}/edit', 'UserController@edit')->name('users.edit');
        Route::put('/users/{user}', 'UserController@update')->name('users.update');
        Route::delete('/users/{user}', 'UserController@destroy')->name('users.destroy');





        Route::get('/roles', 'RoleController@index')->name('roles.index');
        Route::get('/roles/{role}', 'RoleController@show')->name('roles.show');
        Route::get('/roles/{role}/edit', 'RoleController@edit')->name('roles.edit');
        Route::put('/roles/{role}', 'RoleController@update')->name('roles.update');
        Route::delete('/roles/{role}', 'RoleController@destroy')->name('roles.destroy');


        Route::delete('/system/notifications', 'NotificationController@index')->name('notifications.all');


//    Route::get('/categories', 'CategoryController@index')->name('categories.index');//list
//    Route::get('/categories/create', 'CategoryController@create')->name('categories.create');//create
//    Route::post('/categories', 'CategoryController@store')->name('categories.store');//store
//    Route::get('/categories/{category}', 'CategoryController@show')->name('categories.show');//show
//    Route::get('/categories/{category}/edit', 'CategoryController@edit')->name('categories.edit');//edit
//    Route::put('/categories/{category}', 'CategoryController@update')->name('categories.update');//update
//    Route::delete('/categories/{category}', 'CategoryController@destroy')->name('categories.destroy');//destroy


//    put/patch -> update
//    delete -> delete
//    post -> store

        /*Product routes*/


    });

});

//Route::get('/home', function (){
//    return view('backend.home');
//});


Route::get('/cart', 'CartController@shoppingCart')->name('cart');
Route::get('/cart/{productId}/remove', 'CartController@removeFromCart')->name('carts.remove_product');
Route::post('/add-to-cart', 'CartController@addToCart');
Route::get('/{categoryId?}', 'PublicController@index');
Route::get('/category/{category}', 'PublicController@productsByCategoryId')->name('products_by_category');
Route::get('/products/{product}', 'PublicController@show')->name('product_details');


/**Check out Routes */
Route::get('/checkout/index', 'CheckoutController@index')->name('checkout.index');
Route::post('/checkout/store', 'CheckoutController@store')->name('checkout.store');


Route::get('/cart/index', 'CartController@index')->name('cart.index');
Route::post('/cart/store', 'CartController@store')->name('cart.store');
//Route::get('/cart/update', 'CheckoutController@index')->name('cart.index');
//Route::post('/cart/delete', 'CheckoutController@store')->name('cart.delete');

resources/views/backend/sizes/create.blade.php
@extends('backend.layouts.master')

@section('title', 'Size Create')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Sizes</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">Create</h6>
            <a class="btn btn-primary float-right" href="{{ route('sizes.index') }}">List</a>
        </div>
        <div class="card-body">

            @include('backend.layouts.elements.errors')

            {!! Form::open([
                'route' => 'sizes.store'
            ]) !!}

{{--            <form action="{{ route('categories.store') }}" method="post">--}}
{{--                @csrf--}}
                @include('backend.sizes.form')

                <button type="submit" class="btn btn-primary">Submit</button>
{{--            </form>--}}

            {!! Form::close() !!}
        </div>
    </div>
@endsection

@push('js')
    <script>
        // alert('Creating category')
    </script>
@endpush

resources/views/backend/sizes/edit.blade.php
@extends('backend.layouts.master')

@section('title', 'Sizes Update')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Produc</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">Edit</h6>
            <a class="btn btn-primary float-right" href="{{ route('sizes.index') }}">List</a>
        </div>
        <div class="card-body">

            @include('backend.layouts.elements.errors')

            {{--            <form action="{{ route('categories.update', [$category->id]) }}" method="post">--}}
            {{--                @csrf--}}
            {{--                @method('put')--}}

            {!! Form::model($size, [
                            'route' => ['sizes.update', $size->id],
                            'method'=>'put'
                        ]) !!}

            @include('backend.sizes.form')

            <button type="submit" class="btn btn-primary">Submit</button>
            {!! Form::close() !!}
            {{--            </form>--}}
        </div>
    </div>
@endsection

@push('js')
    <script>
        // alert('Creating category')
    </script>
@endpush

resources/views/backend/sizes/form.blade.php
<div class="form-group">
    {{--                    <label for="title">Title</label>--}}
    {!! Form::label('title', 'Title') !!}
    {{--                    <input name="title" type="text" value="{{ old('title') }}" class="form-control" id="title">--}}
    {!! Form::text('title', null, [
        'class'=>'form-control',
        'id'=>'title',
    ]) !!}
</div>

resources/views/backend/sizes/index.blade.php
@extends('backend.layouts.master')

@section('title', 'Size List')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Sizes</h1>
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">List</h6>
\            <a class="btn btn-primary float-right" href="{{ route('sizes.create') }}">Create</a>
        </div>
        <div class="card-body">

            @include('backend.layouts.elements.message')

            <div class="table-responsive">
                <table class="table table-bordered"  width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>SL#</th>
                        <th>Title</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php $sl=0 @endphp
                    @foreach($sizes as $size)
                        <tr>
                            <td>{{ ++$sl }}</td>
                            <td>{{ $size->title }}</td>
                            <td>
                                <a href="{{ route('sizes.show', [$size->id]) }}" class="btn btn-info">Show</a>
                                <a href="{{ route('sizes.edit', [$size->id]) }}" class="btn btn-warning">Edit</a>

                                <form action="{{ route('sizes.destroy', [$size->id]) }}" method="post" style="display: inline">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure want to delete ?')">Delete</button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('css')
    <!-- Custom styles for this page -->
    <link href="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

@push('js')
    <!-- Page level plugins -->
    <script src="{{ asset('ui/backend') }}/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('ui/backend') }}/js/demo/datatables-demo.js"></script>
@endpush

resources/views/backend/sizes/show.blade.php
@extends('backend.layouts.master')

@section('title', 'Category Create')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Categories</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">Details</h6>
            <a class="btn btn-primary float-right" href="{{ route('sizes.index') }}">List</a>
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <td>Title</td>
                    <td>{{ $size->title }}</td>
                </tr>

            </table>

        </div>
    </div>
@endsection

@push('js')
    <script>
        // alert('Creating category')
    </script>
@endpush

resources/views/backend/sizes/trash.blade.php
@extends('backend.layouts.master')

@section('title', 'Deleted Category List')

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Categories</h1>
{{--        <a href="{{ route('categories.download_pdf') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">--}}
{{--            <i class="fas fa-download fa-sm text-white-50"></i> Generate PDF Report--}}
{{--        </a>--}}
{{--        <a href="{{ route('categories.download_excel') }}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm">--}}
{{--            <i class="fas fa-file-excel fa-sm text-white-50"></i> Generate Excel Report--}}
{{--        </a>--}}
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">List</h6>
\            <a class="btn btn-primary float-right" href="{{ route('categories.index') }}">List</a>
        </div>
        <div class="card-body">

            @include('backend.layouts.elements.message')

            <div class="table-responsive">
                <table class="table table-bordered"  width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        <tr>
                            <td>{{ $category->title }}</td>
                            <td>{{ $category->description }}</td>
                            <td>{{ $category->is_active? 'Active' : 'Inactive' }}</td>
                            <td>
                                <a href="{{ route('categories.show', [$category->id]) }}" class="btn btn-info">Show</a>
                                <a href="{{ route('categories.edit', [$category->id]) }}" class="btn btn-warning">Edit</a>

                                <form action="{{ route('categories.destroy', [$category->id]) }}" method="post" style="display: inline">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure want to delete ?')">Delete</button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('css')
    <!-- Custom styles for this page -->
    <link href="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

@push('js')
    <!-- Page level plugins -->
    <script src="{{ asset('ui/backend') }}/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('ui/backend') }}/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('ui/backend') }}/js/demo/datatables-demo.js"></script>
@endpush